services:
  - type: web
    name: gemcart-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
      - key: ADMIN_PASSWORD
        value: sadmin
      - key: WEB_APP_URL
        value: https://primesador-maker.github.io/gemcart/
